name: Multiple Environment Test Suite

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-suite:
    strategy:
      matrix:
        python:
          - version: {{cookiecutter.python_minimum_version}}
            toxenv: {{cookiecutter.python_minimum_version}}
          - version: {{cookiecutter.python_maximum_version}}
            toxenv: {{cookiecutter.python_maximum_version}}
    uses: ./.github/workflows/single-test-suite.yml
    with:
      python_version: {% raw %}${{ matrix.python.version }}{% endraw %}
      toxenv: {% raw %}${{ matrix.python.toxenv }}{% endraw %}
