name: Build package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-wheels:
    name: Build wheels on ${{matrix.os.name}}
    runs-on: ${{matrix.os}}
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - name: ubuntu-20.04
          - name: windows-2019
          - name: macOS-10.15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: "pip"
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.16.2
    - name: Build wheels 
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl



