name: Build Documentation

on:
  pull_request:
    branches:
      - master
      - dev/v[0-9]+.[0-9]+.[0-9]+

permissions:
  # actions: read|write|none
  # checks: read|write|none
  contents: read
  # deployments: read|write|none
  # id-token: read|write|none
  # issues: read|write|none
  # discussions: read|write|none
  # packages: read|write|none
  # pages: read|write|none
  # pull-requests: read|write|none
  # repository-projects: read|write|none
  # security-events: read|write|none
  # statuses: read|write|none


jobs:
  setup-venv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
          python-version: '3.8'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create Virtual Environment
      uses: danoan/setup-python-project-environment-action@v0.1
      with:
        checkout-folder: ${{ github.workspace }}
  check-formatting:
    runs-on: ubuntu-latest
    needs: setup-venv
    steps:
    - uses: actions/setup-python@v4
      with:
          python-version: '3.8'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Restore cache
      uses: danoan/setup-python-project-environment-action@v0.1
      with:
        checkout-folder: ${{ github.workspace }}
    - name: Format check
      run: |
        tox -e format
  check-type:
    runs-on: ubuntu-latest
    needs: setup-venv
    steps:
    - uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Restore cache
      uses: danoan/setup-python-project-environment-action@v0.1
      with:
        checkout-folder: ${{ github.workspace }}
    - name: Type check
      run: |
        tox -e typecheck
  run-tests:
    runs-on: ubuntu-latest
    needs: setup-venv
    steps:
    - uses: actions/setup-python@v4
      with:
          python-version: '3.8'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Restore cache
      uses: danoan/setup-python-project-environment-action@v0.1
      with:
        checkout-folder: ${{ github.workspace }}
    - name: Run tests
      run: |
        tox 
  build-docs:
    permissions:
    # actions: read|write|none
    # checks: read|write|none
      contents: write
    runs-on: ubuntu-latest
    needs: [check-formatting, check-type, run-tests]
    steps:
    - uses: actions/setup-python@v4
      with:
          python-version: '3.8'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Restore cache
      uses: danoan/setup-python-project-environment-action@v0.1
      with:
        checkout-folder: ${{ github.workspace }}
    - name: Build documentation
      run: |
        tox -e docs
    - name: Publish documentation
      run: |
        git clone https://github.com/danoan/python-project-model.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
