name: Single Environment Test suite

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      toxenv:
        required: true
        type: string


jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: ${{ inputs.python_version }}
          cache: "pip"
    - name: Install tox
      run: |
        python -m pip install --upgrade pip && pip install tox
    - name: Format check
      run: |
        tox -e format
  check-type:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: ${{ inputs.python_version }}
          cache: "pip"
    - name: Install tox
      run: |
        python -m pip install --upgrade pip && pip install tox
    - name: Type check
      run: |
        tox -e typecheck
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: ${{ inputs.python_version }}
          cache: "pip"
    - name: Install tox
      run: |
        python -m pip install --upgrade pip && pip install tox
    - name: Run tests
      run: |
        tox -e ${{ inputs.toxenv }}

